//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hudson.TrayTracker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HudsonTrayTrackerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HudsonTrayTrackerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hudson.TrayTracker.HudsonTrayTrackerResources", typeof(HudsonTrayTrackerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hudson Tray Tracker updates.
        /// </summary>
        internal static string ApplicationUpdates_Caption {
            get {
                return ResourceManager.GetString("ApplicationUpdates_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available: v{0}.
        ///Do you want to download it now (the application will be closed)?.
        /// </summary>
        internal static string ApplicationUpdates_NewVersion_Text {
            get {
                return ResourceManager.GetString("ApplicationUpdates_NewVersion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update available..
        /// </summary>
        internal static string ApplicationUpdates_NoUpdate_Text {
            get {
                return ResourceManager.GetString("ApplicationUpdates_NoUpdate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string BuildDetails_Format_NumberDate {
            get {
                return ResourceManager.GetString("BuildDetails_Format_NumberDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}, {2}).
        /// </summary>
        internal static string BuildDetails_Format_NumberDateUsers {
            get {
                return ResourceManager.GetString("BuildDetails_Format_NumberDateUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string BuildDetails_UserSeparator {
            get {
                return ResourceManager.GetString("BuildDetails_UserSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build failed.
        /// </summary>
        internal static string BuildFailed_Caption {
            get {
                return ResourceManager.GetString("BuildFailed_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects regressed.
        /// </summary>
        internal static string BuildRegressions_Caption {
            get {
                return ResourceManager.GetString("BuildRegressions_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build is blocked.
        /// </summary>
        internal static string BuildStatus_Blocked {
            get {
                return ResourceManager.GetString("BuildStatus_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build failed.
        /// </summary>
        internal static string BuildStatus_Failed {
            get {
                return ResourceManager.GetString("BuildStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build failed. Build in progress..
        /// </summary>
        internal static string BuildStatus_Failed_BuildInProgress {
            get {
                return ResourceManager.GetString("BuildStatus_Failed_BuildInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeterminate: no build done..
        /// </summary>
        internal static string BuildStatus_Indeterminate {
            get {
                return ResourceManager.GetString("BuildStatus_Indeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indeterminate: no build done. Build in progress..
        /// </summary>
        internal static string BuildStatus_Indeterminate_BuildInProgress {
            get {
                return ResourceManager.GetString("BuildStatus_Indeterminate_BuildInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build is stuck.
        /// </summary>
        internal static string BuildStatus_Stuck {
            get {
                return ResourceManager.GetString("BuildStatus_Stuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        internal static string BuildStatus_Successful {
            get {
                return ResourceManager.GetString("BuildStatus_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful. Build in progress..
        /// </summary>
        internal static string BuildStatus_Successful_BuildInProgress {
            get {
                return ResourceManager.GetString("BuildStatus_Successful_BuildInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown status.
        /// </summary>
        internal static string BuildStatus_Unknown {
            get {
                return ResourceManager.GetString("BuildStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstable: some tests failed..
        /// </summary>
        internal static string BuildStatus_Unstable {
            get {
                return ResourceManager.GetString("BuildStatus_Unstable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstable: some tests failed. Build in progress..
        /// </summary>
        internal static string BuildStatus_Unstable_BuildInProgress {
            get {
                return ResourceManager.GetString("BuildStatus_Unstable_BuildInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build status.
        /// </summary>
        internal static string DisplayBuildStatus_Caption {
            get {
                return ResourceManager.GetString("DisplayBuildStatus_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects configured.
        /// </summary>
        internal static string DisplayBuildStatus_NoProjects {
            get {
                return ResourceManager.GetString("DisplayBuildStatus_NoProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string ErrorBoxCaption {
            get {
                return ResourceManager.GetString("ErrorBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred:
        ///
        ///Message: {0}.
        /// </summary>
        internal static string ErrorBoxMessage {
            get {
                return ResourceManager.GetString("ErrorBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string FailedLoadingIcons_Caption {
            get {
                return ResourceManager.GetString("FailedLoadingIcons_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed loading icons for the tray notifier..
        /// </summary>
        internal static string FailedLoadingIcons_Text {
            get {
                return ResourceManager.GetString("FailedLoadingIcons_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading projects from {0}.
        /// </summary>
        internal static string FailedLoadingProjects_FormatString {
            get {
                return ResourceManager.GetString("FailedLoadingProjects_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occurred.
        /// </summary>
        internal static string FatalError_Caption {
            get {
                return ResourceManager.GetString("FatalError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error.
        ///
        ///Please refer to the log files for more details..
        /// </summary>
        internal static string FatalError_Message {
            get {
                return ResourceManager.GetString("FatalError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last check: {0}.
        /// </summary>
        internal static string LastCheck_Format {
            get {
                return ResourceManager.GetString("LastCheck_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading projects from {0}.
        /// </summary>
        internal static string LoadingProjects_FormatString {
            get {
                return ResourceManager.GetString("LoadingProjects_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string RunBuildFailed_Caption {
            get {
                return ResourceManager.GetString("RunBuildFailed_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed running build: {0}..
        /// </summary>
        internal static string RunBuildFailed_Text {
            get {
                return ResourceManager.GetString("RunBuildFailed_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred:
        ///
        ///Type: {0}
        ///Message: {1}
        ///
        ///Please refer to the log files for more details.
        ///
        ///The application will now be closed..
        /// </summary>
        internal static string SeriousErrorBoxMessage {
            get {
                return ResourceManager.GetString("SeriousErrorBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version_Format {
            get {
                return ResourceManager.GetString("Version_Format", resourceCulture);
            }
        }
    }
}
