//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hudson.TrayTracker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HudsonTrayTrackerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HudsonTrayTrackerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hudson.TrayTracker.HudsonTrayTrackerResources", typeof(HudsonTrayTrackerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add server.
        /// </summary>
        internal static string AddServer_Caption {
            get {
                return ResourceManager.GetString("AddServer_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in the URL of Hudson&apos;s server:.
        /// </summary>
        internal static string AddServer_Question {
            get {
                return ResourceManager.GetString("AddServer_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string BuildDetails_Format {
            get {
                return ResourceManager.GetString("BuildDetails_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build failed.
        /// </summary>
        internal static string BuildFailed_Caption {
            get {
                return ResourceManager.GetString("BuildFailed_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string ErrorBoxCaption {
            get {
                return ResourceManager.GetString("ErrorBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred:
        ///
        ///Message: {0}.
        /// </summary>
        internal static string ErrorBoxMessage {
            get {
                return ResourceManager.GetString("ErrorBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading projects from {0}.
        /// </summary>
        internal static string FailedLoadingProjects_FormatString {
            get {
                return ResourceManager.GetString("FailedLoadingProjects_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occurred.
        /// </summary>
        internal static string FatalError_Caption {
            get {
                return ResourceManager.GetString("FatalError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error.
        ///
        ///Please refer to the log files for more details..
        /// </summary>
        internal static string FatalError_Message {
            get {
                return ResourceManager.GetString("FatalError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last check: {0}.
        /// </summary>
        internal static string LastCheck_Format {
            get {
                return ResourceManager.GetString("LastCheck_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading projects from {0}.
        /// </summary>
        internal static string LoadingProjects_FormatString {
            get {
                return ResourceManager.GetString("LoadingProjects_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred:
        ///
        ///Type: {0}
        ///Message: {1}
        ///
        ///Please refer to the log files for more details.
        ///
        ///The application will now be closed..
        /// </summary>
        internal static string SeriousErrorBoxMessage {
            get {
                return ResourceManager.GetString("SeriousErrorBoxMessage", resourceCulture);
            }
        }
    }
}
